CREATE TABLE T_BEE_CHAT_CONTACT
(
    ID                BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键',
    WECHAT_ID         VARCHAR(128) COMMENT '微信ID',
    CONTACT_WECHAT_ID VARCHAR(128) COMMENT '联系人微信ID',
    CONTACT_NO        VARCHAR(128) COMMENT '联系人微信号',
    CONTACT_NICKNAME  VARCHAR(256) COMMENT '联系人微信昵称',
    CONTACT_AVATAR    VARCHAR(256) COMMENT '联系人微信头像',
    REMARK            VARCHAR(128) COMMENT '备注',
    CONTACT_TYPE      VARCHAR(2) COMMENT '联系人类型(1:个微联系人,2:企业联系人,3:内部联系人,4:外部联系人)',
    MOBILE            VARCHAR(32) COMMENT '电话',
    LABEL             TEXT COMMENT '标签($标签1$,$标签2$)',
    DESCRIPTION       VARCHAR(256) COMMENT '描述',
    GENDER            VARCHAR(2) COMMENT '性别(0:未知,1:男,2:女)',
    PROVINCE          VARCHAR(64) COMMENT '省份',
    CITY              VARCHAR(64) COMMENT '城市',
    COMPANY_ID        VARCHAR(64) COMMENT '公司ID',
    COMPANY_NAME      VARCHAR(64) COMMENT '公司名称',
    RELATION          VARCHAR(2) COMMENT '联系人关系(1:正常,0:已被删)',
    ADD_CONTACT_TIME  DATETIME COMMENT '添加为联系人时间',
    CREATE_BY         VARCHAR(32) COMMENT '创建人',
    CREATE_TIME       DATETIME COMMENT '创建时间',
    UPDATE_BY         VARCHAR(32) COMMENT '修改人',
    UPDATE_TIME       DATETIME COMMENT '修改时间',
    UNIQUE INDEX IX_T_BEE_CHAT_CONTACT_WC(WECHAT_ID,CONTACT_WECHAT_ID),
    INDEX             IX_T_BEE_CHAT_CONTACT_CWI(CONTACT_WECHAT_ID),
    INDEX             IX_T_BEE_CHAT_CONTACT_ACT(ADD_CONTACT_TIME)
) COMMENT='联系人表' COLLATE=UTF8MB4_UNICODE_CI;

CREATE TABLE T_BEE_CHAT_ROOM
(
    ID              BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键',
    WECHAT_ID       VARCHAR(128) COMMENT '微信ID',
    ROOM_ID         VARCHAR(128) COMMENT '群ID',
    ROOM_NICKNAME   VARCHAR(128) COMMENT '群昵称',
    ROOM_AVATAR     VARCHAR(256) COMMENT '群头像',
    ROOM_TYPE       VARCHAR(2) COMMENT '群类型(1:个微群,2:企微群)',
    OWNER_WECHAT_ID VARCHAR(128) COMMENT '群主微信ID',
    ADMIN_FLAG      VARCHAR(2) COMMENT '群管理标识(1:是,0:否)',
    ME_REMARK       VARCHAR(128) COMMENT '我给本群的备注',
    ROOM_NUM        INT COMMENT '群人数',
    CREATE_BY       VARCHAR(32) COMMENT '创建人',
    CREATE_TIME     DATETIME COMMENT '创建时间',
    UPDATE_BY       VARCHAR(32) COMMENT '修改人',
    UPDATE_TIME     DATETIME COMMENT '修改时间',
    UNIQUE INDEX IX_T_BEE_CHAT_ROOM_WR(WECHAT_ID,ROOM_ID),
    INDEX           IX_T_BEE_CHAT_ROOM_RI(ROOM_ID)
) COMMENT='群表' COLLATE=UTF8MB4_UNICODE_CI;

CREATE TABLE T_BEE_CHAT_ROOM_MEMBER
(
    ID                BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键',
    WECHAT_ID         VARCHAR(128) COMMENT '微信ID',
    ROOM_ID           VARCHAR(128) COMMENT '群ID',
    MEMBER_WECHAT_ID  VARCHAR(128) COMMENT '群成员微信ID',
    MEMBER_NICKNAME   VARCHAR(128) COMMENT '群成员微信昵称',
    MEMBER_AVATAR     VARCHAR(256) COMMENT '群成员微信头像',
    REMARK            VARCHAR(128) COMMENT '备注',
    OWNER_FLAG        VARCHAR(128) COMMENT '群主标识(1:是,0:否)',
    ADMIN_FLAG        VARCHAR(2) COMMENT '群管理标识(1:是,0:否)',
    GENDER            VARCHAR(2) COMMENT '性别(0:未知,1:男,2:女)',
    COMPANY_ID        VARCHAR(64) COMMENT '公司ID',
    COMPANY_NAME      VARCHAR(64) COMMENT '公司名称',
    INVITER_WECHAT_ID VARCHAR(128) COMMENT '邀请人微信ID',
    JOIN_ROOM_TIME    DATETIME COMMENT '进群时间',
    UNIQUE INDEX IX_T_BEE_CHAT_ROOM_MEMBER_WRM(WECHAT_ID,ROOM_ID,MEMBER_WECHAT_ID),
    INDEX             IX_T_BEE_CHAT_ROOM_MEMBER_RM(ROOM_ID,MEMBER_WECHAT_ID),
    INDEX             IX_T_BEE_CHAT_ROOM_MEMBER_MWI(MEMBER_WECHAT_ID),
    INDEX             IX_T_BEE_CHAT_ROOM_MEMBER_IWI(INVITER_WECHAT_ID),
    INDEX             IX_T_BEE_CHAT_ROOM_MEMBER_JRT(JOIN_ROOM_TIME)
) COMMENT='群成员表' COLLATE=UTF8MB4_UNICODE_CI;

CREATE TABLE T_BEE_CHAT_ROOM_ANNCMNT
(
    ID                BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键',
    ROOM_ID           VARCHAR(128) COMMENT '群ID',
    ANNCMNT           TEXT COMMENT '群公告',
    PUBLISH_WECHAT_ID VARCHAR(128) COMMENT '发布人微信ID',
    PUBLISH_NICKNAME  VARCHAR(128) COMMENT '发布人微信昵称',
    PUBLISH_AVATAR    VARCHAR(256) COMMENT '发布人微信头像',
    PUBLISH_TIME      DATETIME COMMENT '发布时间',
    CREATE_BY         VARCHAR(32) COMMENT '创建人',
    CREATE_TIME       DATETIME COMMENT '创建时间',
    UPDATE_BY         VARCHAR(32) COMMENT '修改人',
    UPDATE_TIME       DATETIME COMMENT '修改时间',
    UNIQUE INDEX IX_T_BEE_CHAT_ROOM_ANNCMNT_RI(ROOM_ID)
) COMMENT='群公告表' COLLATE=UTF8MB4_UNICODE_CI;

CREATE TABLE T_BEE_CHAT_MSG
(
    ID             BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键',
    WECHAT_ID      VARCHAR(128) COMMENT '微信ID',
    SENDER         VARCHAR(128) COMMENT '发送人(微信ID|群成员微信ID|模拟群成员微信ID)',
    RECEIVER       VARCHAR(128) COMMENT '接收人(微信ID|群ID|模拟群成员微信ID)',
    MSG_ID         VARCHAR(32) COMMENT '消息ID',
    CONTENT_TYPE   VARCHAR(16) COMMENT '消息类型(@枚举)',
    CONTENT        TEXT COMMENT '消息内容',
    SOURCE         TEXT COMMENT '消息来源(前端不需要)',
    ORIGIN_CONTENT TEXT COMMENT '原始消息内容(前端不需要)',
    REVOKE_FLAG    VARCHAR(2) COMMENT '撤回标识(1:是,0:否)',
    SHIELD_FLAG    VARCHAR(2) COMMENT '屏蔽消息标识(前端不需要)(1:是,0:否)',
    CLIENT_FLAG    VARCHAR(2) COMMENT '客户端消息标识(1:是,0:否)',
    SEND_USER_ID   VARCHAR(32) COMMENT '发送用户ID',
    CREATE_BY      VARCHAR(32) COMMENT '创建人',
    CREATE_TIME    DATETIME COMMENT '创建时间',
    UPDATE_BY      VARCHAR(32) COMMENT '修改人',
    UPDATE_TIME    DATETIME COMMENT '修改时间',
    UNIQUE INDEX IX_T_BEE_CHAT_MSG_WI(WECHAT_ID, MSG_ID),
    INDEX          IX_T_BEE_CHAT_MSG_S(SENDER),
    INDEX          IX_T_BEE_CHAT_MSG_R(RECEIVER),
    INDEX          IX_T_BEE_CHAT_MSG_MI(MSG_ID),
    INDEX          IX_T_BEE_CHAT_MSG_CT(CONTENT_TYPE)
) COMMENT='消息表' COLLATE=UTF8MB4_UNICODE_CI;

CREATE TABLE T_BEE_CHAT_CONVO
(
    ID                   BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键',
    WECHAT_ID            VARCHAR(128) COMMENT '微信ID',
    CONVO_ID             VARCHAR(128) COMMENT '会话ID(微信ID|群ID|模拟群成员微信ID)',
    CONVO_NICKNAME       VARCHAR(128) COMMENT '会话昵称',
    CONVO_AVATAR         VARCHAR(128) COMMENT '会话头像',
    SEND_WECHAT_ID       VARCHAR(128) COMMENT '发送人微信ID',
    SEND_WECHAT_NICKNAME VARCHAR(128) COMMENT '发送人微信昵称',
    SOURCE_ROOM_ID       VARCHAR(128) COMMENT '来源群ID',
    SOURCE_ROOM_NICK     VARCHAR(128) COMMENT '来源群昵称',
    CONVO_TYPE           VARCHAR(2) COMMENT '会话类型(1:私聊,2:群聊,3:模拟)',
    TOP_FLAG             VARCHAR(2) COMMENT '置顶标识(1:已置顶,0:未置顶)',
    DISTURB_FLAG         VARCHAR(2) COMMENT '免打扰标识(1:已免打扰,0:未免打扰)',
    CONTENT              VARCHAR(32) COMMENT '消息内容',
    MSG_TIME             DATETIME COMMENT '消息时间',
    CREATE_BY            VARCHAR(32) COMMENT '创建人',
    CREATE_TIME          DATETIME COMMENT '创建时间',
    UPDATE_BY            VARCHAR(32) COMMENT '修改人',
    UPDATE_TIME          DATETIME COMMENT '修改时间',
    UNIQUE INDEX IX_T_BEE_CHAT_CONVO_WC(WECHAT_ID,CONVO_ID),
    INDEX                IX_T_BEE_CHAT_CONVO_SRI(SOURCE_ROOM_ID),
    INDEX                IX_T_BEE_CHAT_CONVO_MT(MSG_TIME)
) COMMENT='会话表' COLLATE=UTF8MB4_UNICODE_CI;
