syntax = "proto3";

package protobuf.common;

import "google/protobuf/any.proto";
import "consts/EnumContentType.proto";

option java_outer_classname = "MsgNewNoticeProto";

message MsgNewNotice {
  string guid = 1;                                  // 实例ID
  string wechatId = 2;                              // 微信ID
  string senderWechatId = 3;                        // 发送人微信ID(微信ID|群成员微信ID)
  string receiver = 4;                              // 接收人微信ID(微信ID|群ID|模拟群成员微信ID)
  string senderWechatIdNickname = 5;                // 发送人微信昵称
  string senderWechatIdAvatar = 6;                  // 发送人微信头像
  string receiverNickname = 7;                      // 接收人昵称(微信昵称|群昵称|模拟群成员微信昵称)
  string receiverAvatar = 8;                        // 接收人头像(微信头像|群头像|模拟群成员微信头像)
  string msgId = 9;                                 // 消息ID
  string newMsgId = 10;                             // 新消息ID
  int64 msgTime = 11;                               // 消息时间戳(s)
  bool room = 12;                                   // 群消息(true|false)
  bool self = 13;                                   // 自己发的消息(true|false)
  protobuf.consts.EnumContentType contentType = 14; // 消息类型
  google.protobuf.Any content = 15;                 // 消息内容
}

message SysNotice {
  string content = 1; // 系统消息内容
}

message RevokeNotice {
  string content = 1; // 撤回消息内容
  string desc = 2;    // 描述
}

message ReadNotice {

}

message TextNotice {
  string content = 1; // 文本消息内容
  string desc = 2;    // 描述
}

message EmojiNotice {

}

message ImageNotice {

}

message VoiceNotice {

}

message VideoNotice {

}

message WeappNotice {

}

message SphNotice {

}

message LuckymoneyNotice {

}

message LinkNotice {

}

message NamecardNotice {

}

message FileNotice {

}

message QuoteNotice {

}

message ForwardNotice {

}

message TransferNotice {

}